name: Hordes
main: pl.betoncraft.hordes.Hordes
description: Increases amount of mobs near players while decreasing overall number of mobs.
authors: [Co0sh]
version: 1.5
api-version: 1.14
commands:
  hordesreload:
    description: Reloads the configuration
    usage: /<command>
    permission: hordes.reload
permissions:
  hordes.reload:
    default: op